spring:
  application:
    name: OneFin Wallet
  datasource:
    url: jdbc:mysql://localhost:3306/onefin_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  jwt:
#    signerKey: "e331a78798d631d65151bcb13bde7180dcfe38ffc570e9d6c8fdef8641147ab8"
#    valid-duration: 3600
